### ISSUE TITLE
_MQTT_AVAILABILITY_TOPIC_LEGACY does not work with will_set

### ISSUE THREAD

**Issue by phbasler** [fphammerle/switchbot-mqtt#106]
Hi @fphammerle 

I just saw the fix with _MQTT_AVAILABILITY_TOPIC_LEGACY because of the "_" to "-" mixup.

In https://github.com/fphammerle/switchbot-mqtt/blob/9947875774e85ade715fe963d2fa1112624a1394/switchbot_mqtt/__init__.py#L101-L106 you have the for loop which calls will_set twice. While this does not give you an error, it does not work as expected. If you call will_set, it overrides the old will. So in this case the Will is only for the _MQTT_AVAILABILITY_TOPIC_LEGACY and not for _MQTT_AVAILABILITY_TOPIC. You can only have one will in mqtt. 

A possible workaround would be to have a second mqtt client which just has the will and the birth message to the legacy topic and have the original client have the non legacy topic.

But practically spoken: Why not declare it as a bug and make version 3.3.1 with the corrected topic?

**Comment by fphammerle** [comment]
Thanks a lot, @phbasler, for following up and reviewing my changes!

After realizing that I had a mismatch between code and docs in v3.3.0, I was hoping that I could avoid a breaking change that way (but missed to check the docs or properly test the change).

I will follow your suggestion and call it a "fix" rather than a "change".

**Comment by fphammerle** [comment]
released: https://pypi.org/project/switchbot-mqtt/3.3.1/
